Enabled:
  NoContainers:
    approved_images: ['bp-ubuntu-latest-x64-4x']
  SpecialPermissions:
  EmptyName:
  RiskyTriggers:
  UnapprovedRunners:
    allowed_runners: ["bp-ubuntu-latest-x64-4x", "macos-12"]
  CommandInjection:
  AutomaticMerge:
  UnpinnedAction:
    trusted_authors: ["Betterment"]
    loose_validation: false
  UnsafeCheckout:
  InheritedSecrets:
  BulkPermissions:
